-- MySQL Script generated by MySQL Workbench
-- Fri Jul 22 09:30:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema expanses_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `expanses_db` ;

-- -----------------------------------------------------
-- Schema expanses_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `expanses_db` DEFAULT CHARACTER SET utf8 ;
USE `expanses_db` ;

-- -----------------------------------------------------
-- Table `expanses_db`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expanses_db`.`categoria` ;

CREATE TABLE IF NOT EXISTS `expanses_db`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `amount` DOUBLE NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expanses_db`.`lancamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expanses_db`.`lancamento` ;

CREATE TABLE IF NOT EXISTS `expanses_db`.`lancamento` (
  `idLancamento` INT NOT NULL AUTO_INCREMENT,
  `idcategoria` INT NOT NULL,
  `tipo_lancamento` ENUM('pagar', 'receber') NULL,
  `valor` DOUBLE NULL,
  PRIMARY KEY (`idLancamento`),
  INDEX `fk_aancamento_categoria_idx` (`idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_aancamento_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `expanses_db`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expanses_db`.`lancamento_baixas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expanses_db`.`lancamento_baixas` ;

CREATE TABLE IF NOT EXISTS `expanses_db`.`lancamento_baixas` (
  `idlancamento_baixas` INT NOT NULL AUTO_INCREMENT,
  `idLancamento` INT NOT NULL,
  `data_pagamento` DATE NULL,
  `valor_pago` DOUBLE NULL,
  PRIMARY KEY (`idlancamento_baixas`),
  INDEX `fk_lancamento_baixas_lancamento1_idx` (`idLancamento` ASC) VISIBLE,
  CONSTRAINT `fk_lancamento_baixas_lancamento1`
    FOREIGN KEY (`idLancamento`)
    REFERENCES `expanses_db`.`lancamento` (`idLancamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
